In [ ]:
import pandas as pd
import geopandas as gpd

import matplotlib.pyplot as plt
import seaborn as sns


pluto_raw_path = '../data/raw/Primary_Land_Use_Tax_Lot_Output_(PLUTO)_20260314.csv'

pluto = pd.read_csv(pluto_raw_path)

pluto.head()

/tmp/ipykernel_5363/424962448.py:10: DtypeWarning: Columns (17,18,20,21,22,24,25,39,42,44,45,46,47,48,49,52,61,62,69,79,88) have mixed types. Specify dtype option on import or set low_memory=False.
  pluto = pd.read_csv(pluto_raw_path)

,borough,Tax block,Tax lot,community board,census tract 2010,cb2010,schooldist,council district,postcode,firecomp,...,bctcb2020,geom,basempdate,dcasdate,edesigdate,landmkdate,masdate,polidate,rpaddate,zoningdate
0,QN,6173,23,411.0,1123.0,1002.0,26.0,19.0,11361.0,E306,...,4.112300e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,QN,6173,24,411.0,1123.0,1002.0,26.0,19.0,11361.0,E306,...,4.112300e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,QN,6169,26,411.0,1123.0,2000.0,26.0,19.0,11361.0,E306,...,4.112300e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,QN,6172,1,411.0,1123.0,2001.0,26.0,19.0,11361.0,E306,...,4.112300e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,QN,6172,6,411.0,1123.0,2001.0,26.0,19.0,11361.0,E306,...,4.112300e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pluto_gdf = gpd.GeoDataFrame(
  pluto,
  geometry = gpd.points_from_xy(pluto['longitude'], pluto['latitude'], crs="EPSG:2263"))

pluto_gdf.head()

,borough,Tax block,Tax lot,community board,census tract 2010,cb2010,schooldist,council district,postcode,firecomp,...,geom,basempdate,dcasdate,edesigdate,landmkdate,masdate,polidate,rpaddate,zoningdate,geometry
0,QN,6173,23,411.0,1123.0,1002.0,26.0,19.0,11361.0,E306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-73.772 40.769)
1,QN,6173,24,411.0,1123.0,1002.0,26.0,19.0,11361.0,E306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-73.772 40.769)
2,QN,6169,26,411.0,1123.0,2000.0,26.0,19.0,11361.0,E306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-73.774 40.768)
3,QN,6172,1,411.0,1123.0,2001.0,26.0,19.0,11361.0,E306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-73.774 40.767)
4,QN,6172,6,411.0,1123.0,2001.0,26.0,19.0,11361.0,E306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-73.773 40.768)

In [ ]:
cleaned_pluto_gdf = pluto_gdf.copy()

# Standardize column names
cleaned_pluto_gdf.columns= (cleaned_pluto_gdf.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

cleaned_pluto_gdf.head()

,borough,tax_block,tax_lot,community_board,census_tract_2010,cb2010,schooldist,council_district,postcode,firecomp,...,geom,basempdate,dcasdate,edesigdate,landmkdate,masdate,polidate,rpaddate,zoningdate,geometry
0,QN,6173,23,411.0,1123.0,1002.0,26.0,19.0,11361.0,E306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-73.772 40.769)
1,QN,6173,24,411.0,1123.0,1002.0,26.0,19.0,11361.0,E306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-73.772 40.769)
2,QN,6169,26,411.0,1123.0,2000.0,26.0,19.0,11361.0,E306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-73.774 40.768)
3,QN,6172,1,411.0,1123.0,2001.0,26.0,19.0,11361.0,E306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-73.774 40.767)
4,QN,6172,6,411.0,1123.0,2001.0,26.0,19.0,11361.0,E306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-73.773 40.768)

In [ ]:

keep = ['geometry','borough', 'tax_block', 'tax_lot', 'census_tract_2010', 'cb2010', 'council_district', 'postcode', 'policeprct', 'healtharea', 'address', 'zonedist1', 'zonedist2', 'zonedist3', 'zonedist4', 'ltdheight', 'bldgclass', 'landuse', 'easements', 'ownertype', 'ownername', 'lotarea', 'bldgarea', 'resarea', 'garagearea', 'strgearea', 'otherarea', 'areasource', 'numbldgs', 'numfloors', 'unitsres', 'unitstotal', 'lotfront', 'lotdepth', 'bldgfront', 'bldgdepth', 'proxcode', 'irrlotcode', 'lottype', 'assessland', 'assesstot', 'yearbuilt', 'yearalter1', 'yearalter2', 'histdist', 'landmark', 'builtfar', 'residfar', 'borocode', 'bbl', 'tract2010', 'xcoord', 'ycoord', 'latitude', 'longitude', 'zonemap', 'zmcode', 'appbbl', 'appdate', 'plutomapid', 'dcpedited', 'notes', 'bct2020', 'bctcb2020']


dropped_pluto_gdf = cleaned_pluto_gdf[keep]

dropped_pluto_gdf = dropped_pluto_gdf.copy()

dropped_pluto_gdf["yearbuilt_dt"] = pd.to_datetime(
    dropped_pluto_gdf["yearbuilt"],
    format="%Y",
    errors="coerce"
)

dropped_pluto_gdf["yearalter1_dt"] = pd.to_datetime(
    dropped_pluto_gdf["yearalter1"].str.replace(",", ""),
    format="%Y",
    errors="coerce"
)


dropped_pluto_gdf["yearalter2_dt"] = pd.to_datetime(
    dropped_pluto_gdf["yearalter2"].str.replace(",", ""),
    format="%Y",
    errors="coerce"
)




dropped_pluto_gdf.info()
#pluto_owner_types = dropped_pluto_gdf.groupby("ownertype").size()
#pluto_owner_types.head()

#note from talking to Johnny: check type for each column and make sure they make sense.

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 858644 entries, 0 to 858643
Data columns (total 67 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   geometry           858644 non-null  geometry
 1   borough            858644 non-null  object
 2   tax_block          858644 non-null  int64
 3   tax_lot            858644 non-null  int64
 4   census_tract_2010  857235 non-null  float64
 5   cb2010             857235 non-null  float64
 6   council_district   857267 non-null  float64
 7   postcode           856527 non-null  float64
 8   policeprct         856534 non-null  float64
 9   healtharea         856534 non-null  float64
 10  address            858207 non-null  object
 11  zonedist1          856825 non-null  object
 12  zonedist2          19700 non-null   object
 13  zonedist3          218 non-null     object
 14  zonedist4          12 non-null      object
 15  ltdheight          3044 non-null    object
 16  bldgclass          858320 non-null  object
 17  landuse            855931 non-null  float64
 18  easements          858318 non-null  float64
 19  ownertype          35188 non-null   object
 20  ownername          857809 non-null  object
 21  lotarea            857842 non-null  object
 22  bldgarea           858288 non-null  object
 23  resarea            812195 non-null  object
 24  garagearea         812195 non-null  object
 25  strgearea          812195 non-null  object
 26  otherarea          812195 non-null  object
 27  areasource         858318 non-null  float64
 28  numbldgs           857843 non-null  object
 29  numfloors          816281 non-null  float64
 30  unitsres           858199 non-null  object
 31  unitstotal         858200 non-null  object
 32  lotfront           857842 non-null  object
 33  lotdepth           857842 non-null  object
 34  bldgfront          857842 non-null  object
 35  bldgdepth          857842 non-null  object
 36  proxcode           858318 non-null  float64
 37  irrlotcode         858318 non-null  object
 38  lottype            858318 non-null  float64
 39  assessland         858318 non-null  float64
 40  assesstot          858318 non-null  float64
 41  yearbuilt          858318 non-null  float64
 42  yearalter1         858318 non-null  object
 43  yearalter2         858318 non-null  object
 44  histdist           31478 non-null   object
 45  landmark           1469 non-null    object
 46  builtfar           857468 non-null  float64
 47  residfar           858644 non-null  float64
 48  borocode           858644 non-null  int64
 49  bbl                858644 non-null  int64
 50  tract2010          857235 non-null  float64
 51  xcoord             857161 non-null  float64
 52  ycoord             857161 non-null  float64
 53  latitude           857161 non-null  float64
 54  longitude          857161 non-null  float64
 55  zonemap            856884 non-null  object
 56  zmcode             15633 non-null   object
 57  appbbl             100203 non-null  float64
 58  appdate            97743 non-null   object
 59  plutomapid         858644 non-null  int64
 60  dcpedited          41711 non-null   object
 61  notes              0 non-null       float64
 62  bct2020            857235 non-null  float64
 63  bctcb2020          857235 non-null  float64
 64  yearbuilt_dt       818198 non-null  datetime64[ns]
 65  yearalter1_dt      107462 non-null  datetime64[ns]
 66  yearalter2_dt      16914 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(26), geometry(1), int64(5), object(32)
memory usage: 438.9+ MB

In [ ]:
pluto_owner_types = (
    dropped_pluto_gdf.groupby("ownername")
    .size()                     # count parcels per owner
    .sort_values(ascending=False)  # largest first
)

# Top 10 owners
pluto_owner_types.head(10)

ownername
UNAVAILABLE OWNER                                     7678
NYC DEPARTMENT OF PARKS AND RECREATION                5007
NYC DEPARTMENT OF CITYWIDE ADMINISTRATIVE SERVICES    1949
NYC DEPARTMENT OF EDUCATION                           1134
NYC DEPARTMENT OF ENVIRONMENTAL PROTECTION            1015
NYC HOUSING AUTHORITY                                  825
NYC HOUSING PRESERVATION AND DEVELOPMENT               823
NYC DEPARTMENT OF TRANSPORTATION                       670
NAME NOT ON FILE                                       666
NYC TRANSIT AUTHORITY                                  637
dtype: int64

In [ ]:
# List of owners to keep
owners_to_keep = [
    "NYC HOUSING AUTHORITY",
    "NYC HOUSING PRESERVATION AND DEVELOPMENT"
]

# Filter the GeoDataFrame
nycha_housing_gdf = dropped_pluto_gdf[
    dropped_pluto_gdf["ownername"].isin(owners_to_keep)
].copy()  # copy() avoids SettingWithCopyWarning

nycha_housing_gdf.head(20)

,geometry,borough,tax_block,tax_lot,census_tract_2010,cb2010,council_district,postcode,policeprct,healtharea,...,appbbl,appdate,plutomapid,dcpedited,notes,bct2020,bctcb2020,yearbuilt_dt,yearalter1_dt,yearalter2_dt
1890,POINT (-73.966 40.708),BK,2156,21,547.0,1001.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
1941,POINT (-73.965 40.708),BK,2157,19,547.0,1002.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
1952,POINT (-73.966 40.708),BK,2145,28,547.0,1000.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
1953,POINT (-73.966 40.708),BK,2145,29,547.0,1000.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
1954,POINT (-73.967 40.708),BK,2145,30,547.0,1000.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
1955,POINT (-73.967 40.708),BK,2145,32,547.0,1000.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
1958,POINT (-73.967 40.709),BK,2145,33,547.0,1000.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
1959,POINT (-73.967 40.709),BK,2145,34,547.0,1000.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
1960,POINT (-73.967 40.709),BK,2145,35,547.0,1000.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
1961,POINT (-73.966 40.708),BK,2156,22,547.0,1001.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
1962,POINT (-73.966 40.708),BK,2157,1,547.0,1002.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
1963,POINT (-73.966 40.708),BK,2157,3,547.0,1002.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
1964,POINT (-73.966 40.708),BK,2157,4,547.0,1002.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
2011,POINT (-73.966 40.708),BK,2157,5,547.0,1002.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
2023,POINT (-73.965 40.708),BK,2157,21,547.0,1002.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
2024,POINT (-73.965 40.708),BK,2157,22,547.0,1002.0,34.0,11249.0,90.0,500.0,...,NaN,NaN,1,NaN,NaN,3054700.0,3.054700e+10,NaT,NaT,NaT
2524,POINT (-73.976 40.721),MN,356,1,20.0,3003.0,2.0,10009.0,9.0,7600.0,...,NaN,NaN,1,NaN,NaN,1002000.0,1.002000e+10,1950-01-01,NaT,NaT
3926,POINT (-73.937 40.797),MN,1688,45,188.0,2000.0,8.0,10029.0,25.0,2100.0,...,NaN,NaN,1,NaN,NaN,1018800.0,1.018800e+10,1973-01-01,2010-01-01,NaT
4826,POINT (-73.893 40.673),BK,3724,27,1152.0,2004.0,42.0,11207.0,75.0,6100.0,...,NaN,NaN,1,NaN,NaN,3115200.0,3.115200e+10,NaT,NaT,NaT
5237,POINT (-73.893 40.673),BK,3724,29,1152.0,2004.0,42.0,11207.0,75.0,6100.0,...,NaN,NaN,1,NaN,NaN,3115200.0,3.115200e+10,1970-01-01,NaT,NaT

In [ ]:
nycha_housing_gdf.to_csv('../data/processed/cleaned_PLUTO.csv', index=False)